version: '3'
services:
  uwsgi:
    build: ./for_dev
    #container_name: api_server
    ports:
      - "3031:3031"
    tty: yes
    environment:
      TZ: Asia/Tokyo
      FLASK_APP: application/app.py
    depends_on:  # apiサーバーはdbサーバーが立ってから起動
      - db
    networks:  # apiとdbを接続するための共通ネットワーク指定
      - app_net
  db:
    build: ./_mysql
    #container_name: db_server
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: masakick #TODO
      MYSQL_DATABASE: testdb
      TZ: Asia/Tokyo
    volumes:
      - ./_mysql/db-data:/var/lib/mysql
      - ./_mysql/sqls:/docker-entrypoint-initdb.d
    command: mysqld
    networks:
      - app_net
  nginx:
    build: ./nginx
    #container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    #links:
    #  - uwsgi
    ports:
      - "4231:80"
    environment:
      TZ: "Asia/Tokyo"
    networks:
      - app_net
    depends_on:
      - uwsgi
volumes:
  db-data:
networks:
  app_net:
    driver: bridge
